### ISSUE TITLE
Эпизод 1 : переносимость кода

### ISSUE THREAD

**Issue by avasyukov** [EgorMichel/LabMPL#1]
(Этого не было в материалах. И это почти офтоп. Но тем не менее.)

Вот эта строчка:
https://github.com/EgorMichel/LabMPL/blob/bec6ecbce364812f10317b54cba0c2b04fe54465/Furst.py#L7

внезапно не переносима между разными операционными системами.
Потому что разделитель элементов пути по ФС разный в разных ОС. Идейно верно примерно вот так: `os.path.join("dead_moroz", data)`.

**Comment by EgorMichel** [comment]
Спасибо, исправил.

**Comment by avasyukov** [comment]
Починено
