### ISSUE TITLE
Эпизод 3 : pandas

### ISSUE THREAD

**Issue by avasyukov** [EgorMichel/LabMPL#2]
Само по себе использование pandas - ок. Но только тогда это должен быть pandas до конца (и решение будет в 4 раза короче).

Нужно: (а) или использовать pandas со всеми его фичами, (б) или не абьюзить pandas и собирать решение полностью вручную.

**Comment by EgorMichel** [comment]
Спасибо за замечание. Я выбрал вариант (а). Стало в 2 раза короче. После сегодняшнего семинара понял, как должна работать эта библиотека.  Можно ещё как - то улучшить?

**Comment by avasyukov** [comment]
Можно улучшить - `groupby` вместо цикла по `unique`. Но ругаться на это я буду в другой лабе. А здесь уже стало достаточно прилично. Зачтено.
